title: Output Blog
email: takenakaeri0423@gmail.com
description: 日々のひとこと学習ブログ
author: Start Bootstrap
# 本番用（GitHub Pages）
baseurl: "/output_blog"
url: "https://github.com/TakenakaEri"
# 開発用
# baseurl: "/startbootstrap-clean-blog-jekyll/"

# Social Profiles
twitter_username: nakayarn
github_username: TakenakaEri
facebook_username:
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
